name: Build Bootloader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git gettext uuid-dev zlib1g-dev \
          libssl-dev bison flex rsync texinfo bc u-boot-tools device-tree-compiler wget

      - name: Compile U-Boot using build script
        run: |
          chmod +x build.sh
          # 严格按照脚本要求的环境变量格式传参编译
          SOC=mt7981 BOARD=spim-nand ./build.sh
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mt7981-uboot-bin
          path: output/*.bin
