name: Build Bootloader

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk git gettext uuid-dev zlib1g-dev \
          libssl-dev bison flex rsync texinfo bc u-boot-tools device-tree-compiler wget

      - name: Compile U-Boot using build script
        run: |
          chmod +x build.sh
          # 使用自带的 build.sh 传入参数进行编译
          ./build.sh mt7981 spim-nand
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mt7981-uboot-bin
          path: output/*.bin
